#!/bin/bash
# Ehi, Emacs, this is -*- shell-script -*-

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
echo "Script directory: $SCRIPT_DIR"

UNO_ROLES_DIR=$(realpath ${SCRIPT_DIR}/../../infra/ansible/roles/)
EXPORTED_ROLES_DIR=$(realpath ${SCRIPT_DIR}/roles/)

echo "Exported roles: ${EXPORTED_ROLES_DIR}"
echo "Uno roles: ${UNO_ROLES_DIR}"

if [[ -d ${EXPORTED_ROLES_DIR} ]]; then
    ANSIBLE_ROLES=${EXPORTED_ROLES_DIR}
elif [[ -d ${UNO_ROLES_DIR} ]]; then
    ANSIBLE_ROLES=${UNO_ROLES_DIR}
else
    echo "Cannot find a valid ansible role directory"
    exit 1
fi
PLAYBOOK=$(realpath ${ANSIBLE_ROLES}/../playbooks/dev-environment/laptop.yaml)

sudo apt-add-repository --yes ppa:ansible/ansible
sudo apt update
sudo apt-get install --yes ansible

# Later we'll do something like this, but we need to have a way to generate a top-level
# requirements.yaml from all others and export only the subset used here
# (
#     cd ${SCRIPT_DIR}
#     ansible-galaxy install -r requirements.yaml
# )
# for now
ansible-galaxy collection install community.general

echo "Ansible roles: $ANSIBLE_ROLES"
ANSIBLE_ROLES_PATH=${ANSIBLE_ROLES} ansible-playbook -v ${PLAYBOOK}
