
- name: Install python-psutil package, needed for dconf
  apt: name=python3-psutil

- name: setup favorites (linux mint)
  dconf:
    key: "/org/cinnamon/favorite-apps"
    state: present
    value: "['mintinstall.desktop', 'cinnamon-settings.desktop', 'tilix.desktop']"
  when: ansible_facts['distribution'] == 'Linux Mint'

# - name: setup favorites (ubuntu)
#   dconf:
#     key: "/org/gnome/shell/favorite-apps"
#     state: present
#     value: "['com.gexperts.Tilix.desktop']"
#   when: ansible_facts['distribution'] == 'Ubuntu'

- name: setup favorites (ubuntu)
  shell: gsettings set org.gnome.shell favorite-apps "['com.gexperts.Tilix.desktop']"
  when: ansible_facts['distribution'] == 'Ubuntu'
