---

- name: Install packages for font install
  ansible.builtin.apt:
    pkg:
      - wget
  become: true

- name: "Install fonts"
  include_tasks: "download_font_family.yaml"
  loop: "{{font_families}}"
